algo_site/algo/urls.py
from django.urls import path, include

from .import views

app_name = "algo"
urlpatterns = [
    path("", views.index_view, name = "index"),
    path("lg_index", views.lg_index_view, name = "lg_index"),
    path("lg_out", views.lg_out_view, name = "lg_out"),
    path("question/<int:q_id>", views.question_view, name = "question_index"),
    path("req_debug/", views.req_debug_view, name = "req_debug"),
    path("req_submit/", views.req_submit_view, name = "req_submit"),
    path("submission/<int:q_id>", views.submission_view, name = "submission"),
    path("record_item/<int:record_id>/<int:q_id>", views.record_item_view, name = "record_item"),
    path("solution", views.solution_view, name = "solution"),
    path("solution_item/<int:sol_id>", views.solution_item_view, name = "solution_item"),
    path("write_sol", views.write_solution_view, name = "write_sol"),
    path("sol_submit", views.sol_submit, name = "sol_submit"),
    path("req_sol_delete", views.req_sol_delete, name = "req_sol_delete"),
    path("edit_sol", views.edit_sol_view, name = "edit_sol"),
    path("sol_update", views.sol_update_view, name = "sol_update"),
    path("up_vote", views.up_vote_view, name = "up_vote"),
    path("down_vote", views.down_vote_view, name = "down_vote"),
    path("comment_sub", views.comment_sub_view, name = "comment_sub")
]

algo_site/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("algo/", include("algo.urls")),
    path("register/", include("register.urls")),
    path('admin/', admin.site.urls),
]

algo_site/register/urls.py
from django.urls import path, include

from . import views

app_name = "register"
urlpatterns = [
    path("", views.regist, name = "regist"),
    path("confirm/<uuid:code>", views.confirm, name = "confirm"),
    path("lg/", views.lg, name = "lg"),
]

algo_site/algo/models.py
from django.db import models
from register.models import User

class Question(models.Model):
    question_title = models.CharField(max_length = 40)
    question_level = models.IntegerField(default = 1)
    question_text = models.TextField(max_length = 600)
    question_source = models.CharField(max_length = 40)
    question_lable = models.CharField(max_length = 20)
    cin_format = models.TextField(max_length = 300)
    cout_format = models.TextField(max_length = 300)
    data_range = models.TextField(max_length = 300)
    cin_example = models.TextField(max_length = 100)
    cout_example = models.TextField(max_length = 100)
    time_limit = models.IntegerField(default = 1000)
    memory_limit = models.IntegerField(default = 65536)
    test_total = models.IntegerField(default = 1)
    test_path = models.CharField(max_length = 100)

    def __str__(self):
        return self.question_title

class Record(models.Model):
    q_id = models.ForeignKey(Question, on_delete = models.CASCADE)
    u_id = models.ForeignKey(User, on_delete = models.CASCADE)
    status = models.CharField(max_length = 20) 
    code = models.TextField(max_length = 2000)
    lang = models.TextField(max_length = 10)
    time = models.DateTimeField()
    timeused = models.IntegerField(default = 0)
    memoryused = models.IntegerField(default = 0)
    def __str__(self):
        return self.status

class Solution(models.Model):
    author_id = models.ForeignKey(User, on_delete = models.CASCADE)
    qid = models.IntegerField(default = -1)
    title = models.CharField(max_length = 60)
    source_link = models.URLField()
    vote = models.IntegerField(default = 0)
    level = models.IntegerField(default = 0)
    time = models.DateTimeField(default = None)
    content = models.TextField(default = None)

    def __str__(self):
        return self.title

class Sol_vote(models.Model):
    sol_id = models.ForeignKey(Solution, on_delete = models.CASCADE)
    u_id = models.ForeignKey(User, on_delete = models.CASCADE)
    up = models.IntegerField(default = 0)
    down = models.IntegerField(default = 0)

    def __str__(self):
        return self.sol_id.title

class Sol_comment(models.Model):
    sol_id = models.ForeignKey(Solution, on_delete = models.CASCADE)
    u_id = models.ForeignKey(User, on_delete = models.CASCADE)
    time = models.DateTimeField()
    text = models.TextField()

    def __str__(self):
        return self.text
    




# Create your models here.

algo_site/algo/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.views.decorators.csrf import requires_csrf_token
from django.http import JsonResponse
from django.utils import timezone

from .judge import jud
from .models import Question, Record, Solution, Sol_vote, Sol_comment
from register.models import User

import json

import os
import shutil
import sys

judge_path = "/home/pengpeng/workplace/algo/algo_site/algo/judge/judge_space"


def check_session(request):
    if "email" in request.session and "password" in request.session:
        u = User.objects.get(email = request.session["email"])
        res = {
            "exist" : True,
            "uid" : u.pk          
        }
        return res
    else:
        res = {
            "exist": False,
        }

def lg_out_view(request):
    rst = check_session(request)

    u_obj = User.objects.get(pk = rst["uid"])
    del request.session['email'] 
    del request.session["password"]
    return HttpResponseRedirect(reverse("algo:index"))

def index_view(request):
    if "email" in request.session and "password" in request.session:
        u = User.objects.get(email = request.session["email"])
        return HttpResponseRedirect(reverse("algo:lg_index"))
    else:
        context = {}
        context["question_list"] = Question.objects.order_by("pk")
        return render(request, "algo/index.html", context)

def lg_index_view(request):
    rst = check_session(request)
    uid = rst["uid"]
    context = {}
    context["question_list"] = Question.objects.order_by("pk")
    context["u"] = User.objects.get(pk = uid)
    return render(request, "algo/lg_index.html", context)


@requires_csrf_token
def question_view(request, q_id):
    rst = check_session(request)
    context = {}
    if rst["exist"]:
        q = Question.objects.get(pk = q_id)
        context['u'] = User.objects.get(pk = rst["uid"])
        context['q'] = Question.objects.get(pk = q_id)
        context['t_l'] = q.time_limit / 1000
        context['m_l'] = round(q.memory_limit / 1024, 2)
        context['t_l'] = q.time_limit / 1000

        return render(request, "algo/question.html", context)
    else:
        #TODO
        return render(request, "algo/question.html", context)

def req_debug_view(request):
    rec = json.loads(request.body.decode())
    res = {
        "result" : "",
        "cout" : "",
        "true_cout" : "",
        "cin_text" : "",
        "memoryused" : 0, 
        "timeused" : 0 
    }
    code = rec["code"]
    uid = rec["uid"]
    qid = rec["qid"]
    lang = rec["lang"]
    cin_exp = rec["cin_exp"]
    cin_exp = cin_exp.strip(" ")

    cur_name =  str(uid) + "_" + str(qid)
 
    src = judge_path + '/' + cur_name + ".cpp"
    src_f = open(src, "w")
    src_f.write(code)
    src_f.close()
    err =  jud.compile(src, lang, judge_path, cur_name)
    if err:
        res["result"] = err["status"]
        res["cout"] = err["text"]
        #shutil.rmtree(path) 
        os.remove(src)
        return JsonResponse(res)

    q = Question.objects.get(pk = qid)
    ques_info = {
        "t_l" : q.time_limit,
        "m_l" : q.memory_limit
    }

    rst = jud.debug(cin_exp, ques_info, cur_name, judge_path)
    res["result"] = rst["result"]
    if rst["result"] == "Accepted" or rst["result"] == "Presentation Error" or rst["result"] == "Wrong Answer": 
        res["result"] = "Finished"
        res["cout"] = rst["cout"]
    res["cin_text"] = cin_exp
    res["memoryused"] = round(rst["memoryused"] / 1024, 2)
    res["timeused"] = rst["timeused"]
    print(res)
    return JsonResponse(res)



def req_submit_view(request): 
    rec = json.loads(request.body.decode())
    res = {
        "result" : "",
        "cout" : "",
        "true_cout" : "",
        "cin_text" : "",
        "memoryused" : 0, 
        "timeused" : 0 
    }
    code = rec["code"]
    uid = rec["uid"]
    qid = rec["qid"]
    lang = rec["lang"]

    cur_name =  str(uid) + "_" + str(qid)
 
    src = judge_path + '/' + cur_name + ".cpp"
    src_f = open(src, "w")
    src_f.write(code)
    src_f.close()
    err =  jud.compile(src, lang, judge_path, cur_name)
    if err:
        res["result"] = err["status"]
        res["cout"] = err["text"]
        #shutil.rmtree(path) 
        os.remove(src)
        return JsonResponse(res)
    
    q = Question.objects.get(pk = qid)
    ques_info = {
        "t_l" : q.time_limit,
        "m_l" : q.memory_limit
    }

    
    td_path = judge_path + "/testdate/" + str(qid)
    print(td_path)
    td_total = q.test_total
    rst = jud.judge(td_path, td_total, ques_info, cur_name, judge_path)
    
    res["result"] = rst["result"]
    if(res["result"] != "Accepted"):
        if "cout" in rst:
            res["cout"] = rst["cout"]
        if "true_cout" in rst:
            res["true_cout"] = rst["true_cout"]
        res["cin_text"] = rst["cin_text"]
        print(res)
    res["memoryused"] = round(rst["memoryused"] / 1024, 2)
    res["timeused"] = rst["timeused"]
    os.remove(src)

    u = User.objects.get(pk = uid)
    subm = Record.objects.create(q_id = q, u_id = u, status = res["result"], code = code, lang = lang, time =  timezone.now(), 
        timeused = res["timeused"], memoryused = res["memoryused"])
    subm.save()

    return JsonResponse(res) 


def submission_view(request, q_id):
    res = check_session(request)
    q = Question.objects.get(pk = q_id)
    context = {}
    if res["exist"]:
        context = {}
        context["u"] = User.objects.get(pk = res["uid"])
        context["record_list"] = Record.objects.filter(q_id = q_id, u_id = res["uid"] ).order_by("-time")
        context['q'] = q
        return render(request, "algo/submission.html", context)
    else:
        return JsonResponse("res")

def record_item_view(request, record_id, q_id):
    res = check_session(request)
    q = Question.objects.get(pk = q_id)
    record = Record.objects.get(pk = record_id)
    context = {
        "u" : User.objects.get(pk = res["uid"]),
        "q" : q,
        "cur" : record
    }
    return render(request, "algo/record_item.html", context)
        
        
def solution_view(request):
    rst = check_session(request)

    u = User.objects.get(pk = rst["uid"])   
    sol_list = Solution.objects.order_by("-time", "vote")
    context = {}
    context["sol_list"] = sol_list
    context["u"] = u;
    return render(request, "algo/solution.html", context)   

@requires_csrf_token
def solution_item_view(request, sol_id):
    rst = check_session(request)

    u = User.objects.get(pk = rst["uid"])  
    sol_obj = Solution.objects.get(pk = sol_id)

    context = {}
    try:
        sol_vote_obj = Sol_vote.objects.filter(sol_id = sol_obj, u_id = u)[0]
    except:
        context["vote_exist"] = False
    else:
        context["vote_exist"] = True
        context["sol_vote"] = sol_vote_obj
        print(str(sys._getframe().f_lineno) + " sol_vote existed", sol_vote_obj.up, sol_vote_obj.down)

    comment_list = Sol_comment.objects.filter(sol_id = sol_obj)
    context.update({
        "u" : u,
        "sol" : sol_obj,
        "aid" : sol_obj.author_id.pk,
        "content" : json.dumps(sol_obj.content),
        "comment_list": comment_list
    })

    return render(request, "algo/solution_item.html", context)


def write_solution_view(request):
    rst = check_session(request)

    u = User.objects.get(pk = rst["uid"])
    context = {}
    context["u"] = u
    return render(request, "algo/write_sol.html", context)

def sol_submit(request):
    rst = check_session(request)

    author = User.objects.get(pk = rst["uid"])
    qid = request.POST["question_id"]
    title = request.POST["title"]
    level = request.POST["level"]
    source_link = request.POST["source_link"]
    time = timezone.now()
    content = request.POST["mark_text"]

    sol_obj = Solution.objects.create(author_id = author, qid = qid, title = title, source_link = source_link, 
                level =  level,time = time, content = content)
    sol_obj.save()
    return HttpResponseRedirect(reverse("algo:solution_item", args = (sol_obj.pk, )))

def req_sol_delete(request):
    rst = check_session(request)
    req = json.loads(request.body.decode())
    is_del = req["del"]
    res = {}
    if is_del:
        sol_id = req["sol_id"]
        sol_obj = Solution.objects.get(pk = sol_id)
        sol_obj.delete()
        res["has_deleted"] = True
        return JsonResponse(res)

def edit_sol_view(request):
    rst = check_session(request)
    u = User.objects.get(pk = rst["uid"])
    sol_id = request.POST["sol_id"]
    sol_obj = Solution.objects.get(pk = sol_id)
    context = {
        "u" : u,
        "sol" : sol_obj,
        "content" : json.dumps(sol_obj.content),
    }
    print(sol_obj)
    return render(request, "algo/edit_sol.html", context)

def sol_update_view(request):
    rst = check_session(request)

    sol_id = request.POST["sol_id"]
    qid = request.POST["question_id"]
    title = request.POST["title"]
    level = request.POST["level"]
    source_link = request.POST["source_link"]
    time = timezone.now()
    content = request.POST["mark_text"]

    sol_obj = Solution.objects.get(pk = sol_id)
    sol_obj.qid = qid
    sol_obj.title = title
    sol_obj.source_link = source_link
    sol_obj.time = time
    sol_obj.level = level
    sol_obj.content = content
    sol_obj.save()

    return HttpResponseRedirect(reverse("algo:solution_item", args = (sol_obj.pk, )))
    
def up_vote_view(request):
    rst = check_session(request)
    req = json.loads(request.body.decode())
    u = User.objects.get(pk = rst["uid"])

    flag = req["flag"]
    sol_id = req["sol_id"]
    sol_obj = Solution.objects.get(pk = sol_id)
    print(sol_obj)
    sol_obj.vote += flag
    sol_obj.save()
    
    try:
        sol_vote_obj = Sol_vote.objects.filter(sol_id = sol_obj, u_id = u)[0]
        
    except:

algo_site/algo/templates/algo/nav.html
{% load static %}
<link rel = "stylesheet" type = "text/css" href = "{% static 'algo/nav.css' %}">

<nav id = "n_top" class = "nav_top">
    <ul>
        <li><a href="{% url 'algo:lg_index' %}"> 题库 </a> </li>
        <li><a href="{% url 'algo:solution' %}"> 题解 </a> </li>
        <li><a href="#"> 分享 </a> </li>
        <li><a href="#"> 活动 </a> </li>
        <li><a href="#"><strong id = "id_user_username"> {{u.user_name }} </strong></a>
        <ul class="dropdown-menu">
            <li><a href = "#">我的空间</a></li>
            <li><a href = "#">个人信息</a></li>
            <li><a href = "#">修改密码</a></li>
            <li><a href = "{% url 'algo:lg_out' %}">登出</a></li>
        </ul>
        </li>
    </ul>
</nav>

algo_site/algo/templates/algo/record_item.html
<!DOCTYPE html>
<html lang = "zh-CN">
    <head>
        <title> algo </title>
        <meta charset = "utf-8">
        {% load static %}
        <link rel = "stylesheet" type = "text/css" href = "{% static 'algo/question_style.css' %}">
        <link rel="stylesheet" href="{% static 'algo/codemirror-5.52.2/lib/codemirror.css' %}">
        <link rel="stylesheet" href="{% static 'algo/codemirror-5.52.2/theme/seti.css' %}">
        <link rel = "stylesheet" type = "text/css" href = "{% static 'algo/submission_style.css' %}">
        <link rel = "stylesheet" type = "text/css" href = "{% static 'algo/record_item_style.css' %}">

        <script src="{% static 'algo/codemirror-5.52.2/lib/codemirror.js' %}"></script>
        <script src="{% static 'algo/codemirror-5.52.2/mode/clike/clike.js' %}"></script>
        <script src="{% static 'algo/codemirror-5.52.2/addon/edit/matchbrackets.js' %}"></script>

        
    </head>
    <body>
        <div id = "algo_page">
            {% include 'algo/nav.html'%}
            <!--
            <nav id = "n_top" class = "nav_top">
                <div id = "div_top" >
                    <ul class = "ul_top">
                        <li><a href="{% url 'algo:lg_index' u.pk %}"> 题库 </a></li>
                        <li><a href="#"> 题解 </a></li>
                        <li><a href="#"> 分享 </a></li>
                        <li><a href="#"> 活动 </a></li>
                    </ul>
                
                    <ul class = "ul_lg">
                        <li><a href = "#"> {{ u.user_name }} </a></li>
                    </ul>
                </div>
            </nav>
        -->
            <div class = "div_question">
                <div id = "q_title" class = "q_title">
                    <P style = "font-weight: bold;"> {{ q.pk }}.{{ q.question_title }} </P>
                </div>
                <div class = "q_sub">
                    <ul>
                        <li> <a href = "{% url 'algo:question_index' q.pk %}">题目</a></li>
                        <li> <a href = "{% url 'algo:submission' q.pk %}" >提交记录 </a></li>
                        <li> 题解 </li>
                    </ul>
                </div>
            </div> 

               
            <div class = "record_item_code">
                <div id = "lang"> {{ cur.lang }} </div>
                <div>
                    <pre>{{ cur.code }}</pre>
                </div>
            </div>
        </div>
        
        
    </body> 

    <script type="text/javascript">
    </script>

</html>

algo_site/algo/templates/algo/solution_item.html
<!DOCTYPE html>
<html lang = "zh-CN">
    <head>
        <title> algo </title>
        <meta charset = "utf-8">
        {% load static %}
        <link rel = "stylesheet" type = "text/css" href = "{% static 'algo/index_style.css' %}">

        <link rel = "stylesheet" type = "text/css" href = "{% static 'algo/solution.css' %}">
        <link rel = "stylesheet" type = "text/css" href = "{% static 'algo/solution_item.css' %}">

        <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>

    </head>
    <body>
        <div id = "algo_page">

            {% include 'algo/nav.html'%}


            <h2>{{ sol.qid }}.{{ sol.title }}</h2>
            <header class = "info_head">
                <a href = "{{ sol.source_link }}"> 原题链接 </a>
                <div class = "
                            {% if sol.level == 0 %}
                            easy
                            {% elif sol.level == 1 %}
                            middle
                            {% else %}
                            hard
                            {% endif %}
                        ">
                        {% if sol.level == 0 %}
                            简单
                        {% elif sol.level == 1 %}
                            中等
                        {% elif sol.level == 2 %}
                            困难
                        {% endif %}
                </div>
                <div> 作者:
                    <a href = "#"> {{ sol.author_id.user_name }}</a>
                </div>
                <div> {{sol.time}} </div>
                <div class = "author_form">
                    {% if u.pk == aid %}
                    <form method = "POST" action = "{% url 'algo:edit_sol' %}">
                    {% csrf_token %}
                        <input name = "sol_id", value = "{{ sol.pk }}" style = " display : None; " ></input>
                        <button class = "edit_btn" type = "submit" title = "编辑"></button>
                    </form>
                        <button class = "delete_btn" onclick = "on_delete()" title = "删除"> </button>
                    {% endif %}
                </div>
            </header>
            <section>
                {% if vote_exist %}
                <div class = "sol_vote">
                    <button id = "up" class = "{% if sol_vote.up == 0 %}
                                        btn_up
                                    {% elif sol_vote.up > 0 %}
                                        btn_is_up
                                    {% endif %}
                                        " value = "{{ sol_vote.up }}" onclick = "on_up()"></button>
                    <div id = "vote_val" style = "margin-left: 6%;">{{ sol.vote }}</div>
                    <button id = "down" class = "{% if sol_vote.down == 0 %}
                                        btn_down
                                    {% else %}
                                        btn_is_down
                                    {% endif %}
                                        " value = "{{ sol_vote.down }}" onclick= "on_down()"> </button>
                </div>
                {% else %}
                <div class = "sol_vote">
                    <button id = "up" class = "btn_up" value = "{{ sol_vote.up }}" onclick = "on_up()"></button>
                    <div id = "vote_val" style = "margin-left: 6%;">{{ sol.vote }}</div>
                    <button  id = "down" class = "btn_down" value = "{{ sol_vote.up }}" onclick = "on_down()"> </button>
                </div>
                {% endif %}
                <article id = "sol_content" class = "sol_content">
                </article>
                
            </section>
            <article class = "comm_article">
                <div>
                    <h4 style="color:#FF6800">评论</h4>
                    <form class = "comm_form" method = "POST" action = "{% url 'algo:comment_sub' %}">
                    {% csrf_token %}
                        <div>
                            <textarea name = "content" required></textarea>
                            <input type = "text" name = "sol_id" value = " {{ sol.pk }} " style = "display: none;">
                        </div>
                        <div class = "comm_sub_btn">
                            <button type = "submit">提交</button>
                        </div>
                    </form>
                    
                </div>  
                {% for comm in comment_list %}
                <hr style="border: 1px solid #D9D9D9;">
                <div class = "comm_list">
                    <div class = "usr_and_time">
                        <a href = "#" style = "color: #247459">{{ comm.u_id.user_name }}</a>
                        <span>{{ comm.time }}</span>
                    </div>
                    <pre>{{ comm.text }}</pre>
                </div>
                {% endfor %}
            </article>

        </div>
        
        
    </body> 


    <script type = "text/javascript">
        function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie !== '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = cookies[i].trim();
                            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }       

        var sol_content = {{ content | safe}};
        document.getElementById('sol_content').innerHTML = marked(sol_content);

        var sol_id = {{ sol.pk }};

        function on_edit() {
            var edit_req = new XMLHttpRequest();
            edit_req.onreadystatechange = function() {
                    if(edit_req.readyState == 4 && edit_req.status == 200) {
                        var rst = JSON.parse(edit_req.responseText);
                            window.location.replace("{% url 'algo:solution' %}");
                    }
                }

            edit_req.open("POST", "{% url 'algo:edit_sol' %}", true);
            var data = JSON.stringify({
                "sol_id" : sol_id
            });
            console.log(data)
            var csrftoken = getCookie('csrftoken');
            edit_req.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            edit_req.setRequestHeader('X-CSRFToken', csrftoken);
            edit_req.send(data);   
    }

        function on_delete() {
            if(confirm("确认删除?") == true) {
                var del_req = new XMLHttpRequest();

                del_req.onreadystatechange = function() {
                    if(del_req.readyState == 4 && del_req.status == 200) {
                        var rst = JSON.parse(del_req.responseText);
                        console.log(rst);
                        if(rst.has_deleted ) {
                            alert("成功删除数据");
                            window.location.replace("{% url 'algo:solution' %}");
                        }
                    }
                }

                del_req.open("POST", "{% url 'algo:req_sol_delete' %}", true);
                var data = JSON.stringify({
                    "del" : true,
                    "sol_id" : sol_id
                });
                console.log(data)
                var csrftoken = getCookie('csrftoken');
                del_req.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                del_req.setRequestHeader('X-CSRFToken', csrftoken);
                del_req.send(data);                   
            }
            else
                alert("取消删除数据");
        }

        var sol_id = {{ sol.pk | safe}};
        function on_up(){
            var up_req = new XMLHttpRequest();
            up_req.open("POST", "{% url 'algo:up_vote' %}", true);
            var value = document.getElementById("up").getAttribute("value");
            var flag = 0
            var vote_val = document.getElementById("vote_val").innerText;
            if(value == 0) {
                flag = 1;
                document.getElementById("up").setAttribute("class", "btn_is_up" );
                document.getElementById("up").setAttribute("value", "1");       
                vote_val = parseInt(vote_val, 10)
                vote_val += 1;
                document.getElementById("vote_val").innerHTML = vote_val;
            }
            else {
                flag = -1;
                document.getElementById("up").setAttribute("class", "btn_up");
                document.getElementById("up").setAttribute("value", "0" ); 
                vote_val = parseInt(vote_val, 10)
                vote_val -= 1;
                document.getElementById("vote_val").innerHTML = vote_val;
            }

            var data = JSON.stringify({
                "flag" : flag,
                "sol_id": sol_id,
            });
            var csrftoken = getCookie('csrftoken');
            up_req.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            up_req.setRequestHeader('X-CSRFToken', csrftoken);
            up_req.send(data);         
        }

        function on_down(){
            var up_req = new XMLHttpRequest();
            up_req.open("POST", "{% url 'algo:down_vote' %}", true);
            var value = document.getElementById("down").getAttribute("value");
            var flag = 0
            var vote_val = document.getElementById("vote_val").innerText;
            if(value == 0) {
                flag = -1;
                document.getElementById("down").setAttribute("class", "btn_is_down" );
                document.getElementById("down").setAttribute("value", "1");       
                vote_val = parseInt(vote_val, 10)
                vote_val -= 1;
                document.getElementById("vote_val").innerHTML = vote_val;
            }
            else {
                flag = 1;
                document.getElementById("down").setAttribute("class", "btn_down");
                document.getElementById("down").setAttribute("value", "0" ); 
                vote_val = parseInt(vote_val, 10)
                vote_val += 1;
                document.getElementById("vote_val").innerHTML = vote_val;
            }

            var data = JSON.stringify({
                "flag" : flag,
                "sol_id": sol_id,
            });
            var csrftoken = getCookie('csrftoken');
            up_req.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            up_req.setRequestHeader('X-CSRFToken', csrftoken);
            up_req.send(data);         
        }
    </script>
</html>

algo_site/algo/templates/algo/submission.html
<!DOCTYPE html>
<html lang = "zh-CN">
    <head>
        <title> algo </title>
        <meta charset = "utf-8">
        {% load static %}
        <link rel = "stylesheet" type = "text/css" href = "{% static 'algo/question_style.css' %}">
        <link rel="stylesheet" href="{% static 'algo/codemirror-5.52.2/lib/codemirror.css' %}">
        <link rel="stylesheet" href="{% static 'algo/codemirror-5.52.2/theme/seti.css' %}">
        <link rel = "stylesheet" type = "text/css" href = "{% static 'algo/submission_style.css' %}">

        <script src="{% static 'algo/codemirror-5.52.2/lib/codemirror.js' %}"></script>
        <script src="{% static 'algo/codemirror-5.52.2/mode/clike/clike.js' %}"></script>
        <script src="{% static 'algo/codemirror-5.52.2/addon/edit/matchbrackets.js' %}"></script>

        
    </head>
    <body>
        <div id = "algo_page">
            {% include 'algo/nav.html'%}
            
            <div>
                <div class = "div_question">
                    <div id = "q_title" class = "q_title">
                        <P style = "font-weight: bold;"> {{ q.pk }}.{{ q.question_title }} </P>
                    </div>
                    <div class = "q_sub">
                        <ul>
                            <li> <a href = "{% url 'algo:question_index' q.pk %}">题目</a> </li>
                            <li> <a href = "{% url 'algo:submission' q.pk %}" >提交记录 </a></li>
                            <li> 题解 </li>
                        </ul>
                    </div>
                </div>
                <div >
                    <table class = "record_table">
                        <thead>
                            <tr class = "record_tr"> 
                                <th> 提交时间 </th>
                                <th> 状态</th>
                                <th> 运行时间</th>
                                <th> 运行空间</th>
                                <th> 语言 </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for v in record_list %}
                            <tr class = "record_tr">
                                <td>{{ v.time }}</td>
                                <td><a class = "
                                    {% if v.status == "Accepted" %} 
                                        AC
                                    {% else %}
                                        NOT_AC
                                    {% endif %}
                                    "
                                     href = {% url 'algo:record_item' v.pk q.pk %}> {{ v.status }}</a></td>
                                <td>{{ v.timeused }}s</td>
                                <td>{{ v.memoryused }}MB</td>
                                <td>{{ v.lang }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
               
            </div>

        </div>
        
        
    </body> 

    <script type="text/javascript">
        

    </script>

</html>