algo_site/algo/urls.py
from django.urls import path, include

from .import views

app_name = "algo"
urlpatterns = [
    path("", views.index_view, name = "index"),
    path("lg_index", views.lg_index_view, name = "lg_index"),
    path("lg_out", views.lg_out_view, name = "lg_out"),
    path("question/<int:q_id>", views.question_view, name = "question_index"),
    path("req_debug/", views.req_debug_view, name = "req_debug"),
    path("req_submit/", views.req_submit_view, name = "req_submit"),
    path("submission/<int:q_id>", views.submission_view, name = "submission"),
    path("record_item/<int:record_id>/<int:q_id>", views.record_item_view, name = "record_item"),
    path("solution", views.solution_view, name = "solution"),
    path("solution_item/<int:sol_id>", views.solution_item_view, name = "solution_item"),
    path("write_sol", views.write_solution_view, name = "write_sol"),
    path("sol_submit", views.sol_submit, name = "sol_submit"),
    path("req_sol_delete", views.req_sol_delete, name = "req_sol_delete"),
    path("edit_sol", views.edit_sol_view, name = "edit_sol"),
    path("sol_update", views.sol_update_view, name = "sol_update"),
    path("up_vote", views.up_vote_view, name = "up_vote"),
    path("down_vote", views.down_vote_view, name = "down_vote"),
    path("comment_sub", views.comment_sub_view, name = "comment_sub")
]

algo_site/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("algo/", include("algo.urls")),
    path("register/", include("register.urls")),
    path('admin/', admin.site.urls),
]

algo_site/register/urls.py
from django.urls import path, include

from . import views

app_name = "register"
urlpatterns = [
    path("", views.regist, name = "regist"),
    path("confirm/<uuid:code>", views.confirm, name = "confirm"),
    path("lg/", views.lg, name = "lg"),
]

algo_site/register/models.py
from django.db import models

class User(models.Model):
    user_name = models.CharField(max_length = 20)
    email = models.EmailField()
    password = models.CharField(max_length = 20)
    has_confirmed = models.BooleanField(default=False)
    def __str__(self):
        return self.user_name
class ConfirmString(models.Model):
    code = models.CharField(max_length = 256)
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    c_time = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.user.user_name + ":" + self.code


# Create your models here.

algo_site/register/views.py
import datetime
import pytz

from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.urls import reverse

from . models import User
from . import models

def make_confirm_string(user):
    from uuid import uuid4
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%s")
    code = str(uuid4())
    models.ConfirmString.objects.create(code = code, user = user)
    return code

def regist(request):
    if request.method == "GET":
        context = {}
        context['prev_page'] = request.GET.get("from_page")
        return render(request, "register/register.html", context)
    else:
        name = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        context = {}
        flag = False
        if User.objects.filter(user_name = name).exists():
            context["error_name"] = "用户名已存在"
            flag = True
        if User.objects.filter(email = email).exists():
            context["error_email"] = "邮箱已存在"
            flag = True
        if flag:
            context['prev_page'] = request.POST.get("from_page")
            return render(request, "register/register.html", context)
        else:
            user = User.objects.create(user_name = name, password = password, email = email)
            user.save()
            code = make_confirm_string(user)
            send_email(email, code)
            message = "请前往注册邮箱, 进行邮件确认"
            return render(request, 'register/confirm.html', locals())
            
def send_email(email, code):
    from django.core.mail import EmailMultiAlternatives
    subject = "来自algo的注册邮件"
    text_content = "你的邮箱服务不支持html格式, 无法完成验证"
    html_content = ''' <h3>感谢注册</h3>
                    <p>点击<a href = "http://{}/register/confirm/{}" target = blank >www.register.link</a>完成注册确认</p>
                    <p> 此链接有效期为{}天 </p>
                    '''.format("172.20.10.11:8000", code, settings.CONFIRM_DAYS)
    msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()

def confirm(request, code):
    message = ""
    try:
        confirm = models.ConfirmString.objects.get(code = code) 
    except:
        message = "无效的确认请求"
        return render(request, "register/confirm.html", locals())
    c_time = confirm.c_time
    now = datetime.datetime.now()
    now = now.replace(tzinfo = pytz.timezone("UTC"))
    if now > c_time + datetime.timedelta(settings.CONFIRM_DAYS):
        confirm.user.delete()
        message = "你的邮件已经过期, 请重新注册"
        return render(request, "register/confirm.html", locals())
    else:
        confirm.user.has_confirmed = True
        confirm.user.save()
        confirm.delete()
        message = "注册成功, 开始刷题之旅吧"
        return render(request, "register/confirm.html", locals())

def lg(request):
    if request.method == "GET":
        return render(request, "register/lg.html");
    else:
        email = request.POST["email"]
        password = request.POST["password"]
        context = {}
        flag = False
        if not User.objects.filter(email = email).exists():
            context["error_email"] = "邮箱不存在"
            flag = True
        else :
            u = models.User.objects.get(email = email)
            if not u.has_confirmed:
                flag = True
                context["error_email"] = "邮箱没有注册"
            if u.password != password:
                flag = True
                context["error_password"] = "密码错误"
        if flag:
            return render(request, "register/lg.html", context)
        else:
            request.session["email"] = email
            request.session["password"] = password

            return HttpResponseRedirect(reverse("algo:lg_index"))

algo_site/register/templates/register/confirm.html
{% block title %}注册确认{% endblock %}
{% block content %}
    <div class="row">
        <h1 class="text-center">{{ message }}</h1>
    </div>
   
{% endblock %}

algo_site/register/templates/register/lg.html
<!DOCTYPE html>
<html lang = "zh-CN">
    <head>
        <title> algo </title>
        <meta charset = "utf-8">
        <style type = "text/css">
            body {
                font: 12px 'Lucida sns Unicode', 'Trebuchet MS', Arial, helvetica;
                margin: 0;
                background-color: #d9dee2;
            }
            #login {
                background-color: #fff;
                height: 240px;
                width: 400px;
                margin: -150px 0 0 -230px;
                padding: 30px;
                position: absolute;
                top: 50%;
                left: 50%;
                z-index: 0;
                border-radius: 5px;
                box-shadow:
                    0 0 2px rgba(0, 0, 0, 0.2),
                    0 1px 1px rgba(0, 0, 0, .2),
                    0 3px 0 #fff,
                    0 4px 0 rgba(0, 0, 0, .2),
                    0 6px 0 #fff,
                    0 7px 0 rgba(0, 0, 0, .2);

            }
            #login h1{
                text-align: center;
                letter-spacing: 20px;
                color : #B3AEAE;
                box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0, 1px 0 rgba(255, 255, 255, 0.3) inset;
            }

            fieldset {
                border: 0;
                padding: 0;
                margin: 0;
            }
            #inputs input {
                padding: 15px 15px 15px 30px;
                margin:0 0 10px 0;
                width: 353px;
                border: 1px solid #ccc;
                border-radius: 5px;
                box-shadow: 0 1px 1px #ccc inset, 0 1px 9 #fff;
            }
            #inputs input:focus {
                background-color: #fff;
                border-color: #e8c291;
                outline: none;
                box-shadow: 0 0 0 1px #e8c291 inset;
            }
            #actions {
                margin: 25px 0 0 0;
            }
            #submit {
                background-color: #ffb94b;
                border-radius: 3px;
                text-shadow: 0 1px 0 rgba(255, 255, 255, 0.5);
                box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0, 1px 0 rgba(255, 255, 255, 0.3) inset;
                border-width: 1px;
                border-style: soild;
                border-color: #d69e31 #e3a037 #d5982d #e3a037;

                float: left;
                height: 35px;
                padding: 0;
                width: 120px;
                cursor: pointer;
                font: bold 15pxs Arial helvetica;
                color: #8f5a0a;
            }

            #actions a {
                color: #3151A2;
                float: right;
                line-height: 35px;
                margin-left: 10px;
            }
        </style>
    </head>
    <body>
        <form id = "login" method = "POST" action = "/register/lg/">
            {% csrf_token %} 
            <h1> 登陆 </h1>
            <fieldset id = "inputs">
                <input id = "email" name = "email" type = "text" placeholder = "邮箱" autofucus required>
                    <span id = "r_email"> <font color = '#EC0808'> {{ error_email}} </font> </span>
                <input id = "password" name = "password" type = "password" placeholder = "密码" required>
                    <span id = "r_email"> <font color = '#EC0808'> {{ error_password}} </font> </span>
            </fieldset>
            <fieldset id = "actions">
                <input type = "submit" id = "submit" value = "登录" >
                <a href = ""> 忘记密码? </a> <a href = "{% url 'register:regist' %}"> 注册用户</a> 
            </fieldset>
        </form>
    </body> 
    <script>
    </script>
</html>

algo_site/register/templates/register/register.html
<!DOCTYPE html>
<html lang = "zh-CN">
    <head>
        <title> algo </title>
        <meta charset = "utf-8">
        <style type = "text/css">
            body {
                font: 12px 'Lucida sns Unicode', 'Trebuchet MS', Arial, helvetica;
                margin: 0;
                background-color: #d9dee2;
            }
            #sign_in {
                background-color: #fff;
                height: 340px;
                width: 400px;
                margin: -150px 0 0 -230px;
                padding: 30px;
                position: absolute;
                top: 50%;
                left: 50%;
                z-index: 0;
                border-radius: 5px;
                box-shadow:
                    0 0 2px rgba(0, 0, 0, 0.2),
                    0 1px 1px rgba(0, 0, 0, .2),
                    0 3px 0 #fff,
                    0 4px 0 rgba(0, 0, 0, .2),
                    0 6px 0 #fff,
                    0 7px 0 rgba(0, 0, 0, .2);

            }
            #sign_in h1{
                text-align: center;
                letter-spacing: 20px;
                color : #B3AEAE;
                box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0, 1px 0 rgba(255, 255, 255, 0.3) inset;
            }

            fieldset {
                border: 0;
                padding: 0;
                margin: 0;
            }
            #inputs input {
                padding: 15px 15px 15px 30px;
                margin:0 0 10px 0;
                width: 353px;
                border: 1px solid #ccc;
                border-radius: 5px;
                box-shadow: 0 1px 1px #ccc inset, 0 1px 9 #fff;
            }
            #inputs input:focus {
                background-color: #fff;
                border-color: #78F06B;
                outline: none;
                box-shadow: 0 0 0 1px #78F06B inset;
            }
            #actions {
                margin: 25px 0 0 0;
            }
            #submit {
                background-color: #78F06B;
                border-radius: 3px;
                text-shadow: 0 1px 0 rgba(255, 255, 255, 0.5);
                box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0, 1px 0 rgba(255, 255, 255, 0.3) inset;
                border-width: 1px;
                border-style: soild;
                border-color: #4cd631 #37e393 #2dd5a3 #37e36b;

                float: left;
                height: 35px;
                padding: 0;
                width: 120px;
                cursor: pointer;
                font: bold 15pxs Arial helvetica;
                color: rgb(95, 99, 95);
            }

            #actions a {
                color: #3151A2;
                float: right;
                line-height: 35px;
                margin-left: 10px;
            }
        </style>
    </head>
    <body>
        <form id = "sign_in" method = "post" action = "/register/from_page = {{ prev_page }}"> 
            {% csrf_token %}
            <h1> 注册 </h1>
            <fieldset id = "inputs">
                <input id = "username" name = "username" type = "text" placeholder = "用户名" autofucus required>
                   <span id = "r_name"> <font color = '#EC0808' > {{ error_name}} </font> </span>
                <input id = "email" name = "email" type = "email" placeholder = "邮箱" required>
                    <span id = "r_email"> <font color = '#EC0808'> {{ error_email}} </font> </span>
                <input id = "password" name = "password" type = "password" placeholder = "密码" required><span id = "r_password"></span>
                <input id = "confirm_password" type = "password" placeholder = "确认密码" onkeyup = "check()" required><span id = "equ"></span>
            </fieldset>
            <fieldset id = "actions">
                <input type = "submit" id = "submit"  value = "注册" >
                <a href = "{% url 'register:lg' %}"> 已有账户? 请登陆 </a>
            </fieldset>
        </form>
    </body> 
    <script type = "text/javascript">
        function check() {
            var p1 = document.getElementById("password").value;
            var p2 = document.getElementById("confirm_password").value;
            if(p1 != p2) {
                document.getElementById("equ").innerHTML = "<font color = '#EC0808'> 两次密码不一致 无法提交</font>";
                document.getElementById("submit").disabled = true;    
            }   
            else {
                document.getElementById("equ").innerHTML = "<font color = 'green'> 两次密码一致 </font>";
                document.getElementById("submit").disabled = false;    
            }    
        }
    </script>
</html>